#!/usr/bin/env bash
# This script displays 0 to 12 hours of a clock and 1 to 59 minutes for each
h_counter=0
m_counter=1
while [ "$h_counter" -le 12 ]; do
	echo "Hour: $h_counter"
	while [ "$m_counter" -le 59 ]; do
		echo "$m_counter"
		((m_counter++))
	done
	((m_counter=1))
	((h_counter++))
done
